const nodes = [
    {id:	1	, name: 	 ' 	Astral map	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	astral-map		 '	},
    {id:	2	, name: 	 ' 	Bacteriophage ms2 capsid protein : RNA complex   	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	bacteriophage-ms2-capsid-protein-rna-complex		 '	},
    {id:	3	, name: 	 ' 	Infernal spiral	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	infernal-spiral		 '	},
    {id:	4	, name: 	 ' 	Phylogenèse	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	phylogenese		 '	},
    {id:	5	, name: 	 ' 	Baboon/human comparison	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	baboon-human-comparison		 '	},
    {id:	6	, name: 	 ' 	CMS collisions	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	cms-collisions		 '	},
    {id:	7	, name: 	 ' 	Politics	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	politics		 '	},
    {id:	8	, name: 	 ' 	Star wars interactions	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	star-wars-interactions		 '	},
    {id:	9	, name: 	 ' 	NERF(s)	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	nerfs		 '	},
    {id:	10	, name: 	 ' 	Souvenir	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	souvenir		 '	},
    {id:	11	, name: 	 ' 	Le bal des nuées oiseaux	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	le-bal-des-nuees-oiseaux		 '	},
    {id:	12	, name: 	 ' 	La danse des bancs de poissons	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	la-danse-des-bancs-de-poissons		 '	},
    {id:	13	, name: 	 ' 	Mirage festival 	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	mirage-festival		 '	},
    {id:	14	, name: 	 ' 	Mirage festival 	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	mirage-festival		 '	},
    {id:	15	, name: 	 ' 	Dimension festival	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	dimension-festival		 '	},
    {id:	16	, name: 	 ' 	L’origine du monde	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	l-origine-du-monde		 '	},
    {id:	17	, name: 	 ' 	Synesthésies	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	synesthesies		 '	},
    {id:	18	, name: 	 ' 	Desigual	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	desigual		 '	},
    {id:	19	, name: 	 ' 	Emergence	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	emergence		 '	},
    {id:	20	, name: 	 ' 	Année 2090	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	annee-2090		 '	},
    {id:	21	, name: 	 ' 	Assises Internationales du Roman	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	assises-internationales-du-roman		 '	},
    {id:	22	, name: 	 ' 	.json	 ' 	, type:	 ' 	data-file-extension	 ' 	, url:' /	tags-list			 '	},
    {id:	23	, name: 	 ' 	.csv	 ' 	, type:	 ' 	data-file-extension	 ' 	, url:' /	tags-list			 '	},
    {id:	24	, name: 	 ' 	.pdb	 ' 	, type:	 ' 	data-file-extension	 ' 	, url:' /	tags-list			 '	},
    {id:	25	, name: 	 ' 	.nex	 ' 	, type:	 ' 	data-file-extension	 ' 	, url:' /	tags-list			 '	},
    {id:	26	, name: 	 ' 	.obj	 ' 	, type:	 ' 	data-file-extension	 ' 	, url:' /	tags-list			 '	},
    {id:	27	, name: 	 ' 	.xml	 ' 	, type:	 ' 	data-file-extension	 ' 	, url:' /	tags-list			 '	},
    {id:	28	, name: 	 ' 	.xyz 	 ' 	, type:	 ' 	data-file-extension	 ' 	, url:' /	tags-list			 '	},
    {id:	29	, name: 	 ' 	.geojson	 ' 	, type:	 ' 	data-file-extension	 ' 	, url:' /	tags-list			 '	},
    {id:	30	, name: 	 ' 	.newick	 ' 	, type:	 ' 	data-file-extension	 ' 	, url:' /	tags-list			 '	},
    {id:	31	, name: 	 ' 	.gltf 	 ' 	, type:	 ' 	data-file-extension	 ' 	, url:' /	tags-list			 '	},
    {id:	32	, name: 	 ' 	xyz cartesian coordinates	 ' 	, type:	 ' 	data type	 ' 	, url:' /	tags-list			 '	},
    {id:	33	, name: 	 ' 	mesh	 ' 	, type:	 ' 	data type	 ' 	, url:' /	tags-list			 '	},
    {id:	34	, name: 	 ' 	décimal (float)	 ' 	, type:	 ' 	data type	 ' 	, url:' /	tags-list			 '	},
    {id:	35	, name: 	 ' 	Atomicité 	 ' 	, type:	 ' 	data type	 ' 	, url:' /	tags-list			 '	},
    {id:	36	, name: 	 ' 	sequence alignment matrix/taxonomy /trees	 ' 	, type:	 ' 	data type	 ' 	, url:' /	tags-list			 '	},
    {id:	37	, name: 	 ' 	tracks / vectors	 ' 	, type:	 ' 	data type	 ' 	, url:' /	tags-list			 '	},
    {id:	38	, name: 	 ' 	cameras positions alignement	 ' 	, type:	 ' 	data type	 ' 	, url:' /	tags-list			 '	},
    {id:	39	, name: 	 ' 	edges	 ' 	, type:	 ' 	data type	 ' 	, url:' /	tags-list			 '	},
    {id:	40	, name: 	 ' 	.jpeg	 ' 	, type:	 ' 	data-file-extension	 ' 	, url:' /	tags-list			 '	},
    {id:	41	, name: 	 ' 	.gif	 ' 	, type:	 ' 	data-file-extension	 ' 	, url:' /	tags-list			 '	},
    {id:	42	, name: 	 ' 	bla 1	 ' 	, type:	 ' 	idem	 ' 	, url:' /	tags-list			 '	},
    {id:	43	, name: 	 ' 	bla 2	 ' 	, type:	 ' 	idem	 ' 	, url:' /	tags-list			 '	},
    {id:	44	, name: 	 ' 	bla 3	 ' 	, type:	 ' 	idem	 ' 	, url:' /	tags-list			 '	},
    {id:	45	, name: 	 ' 	bla 4	 ' 	, type:	 ' 	idem	 ' 	, url:' /	tags-list			 '	},
    {id:	46	, name: 	 ' 	bla 5	 ' 	, type:	 ' 	idem	 ' 	, url:' /	tags-list			 '	},
    {id:	47	, name: 	 ' 	bla 6	 ' 	, type:	 ' 	idem	 ' 	, url:' /	tags-list			 '	},
    {id:	48	, name: 	 ' 	bla 7	 ' 	, type:	 ' 	idem	 ' 	, url:' /	tags-list			 '	},
    {id:	49	, name: 	 ' 	formulas	 ' 	, type:	 ' 	data type	 ' 	, url:' /	tags-list			 '	},
    {id:	50	, name: 	 ' 	points cloud coordinates, Vertex RGB color	 ' 	, type:	 ' 	data type	 ' 	, url:' /	tags-list			 '	},
    {id:	51	, name: 	 ' 	Dictionary 	 ' 	, type:	 ' 	IDE	 ' 	, url:' /	tags-list			 '	},
    {id:	52	, name: 	 ' 	Jupyter notepad 	 ' 	, type:	 ' 	IDE	 ' 	, url:' /	tags-list			 '	},
    {id:	53	, name: 	 ' 	Visual Studio Code	 ' 	, type:	 ' 	IDE	 ' 	, url:' /	tags-list			 '	},
    {id:	54	, name: 	 ' 	Codepen	 ' 	, type:	 ' 	IDE	 ' 	, url:' /	tags-list			 '	},
    {id:	55	, name: 	 ' 	Github	 ' 	, type:	 ' 	IDE	 ' 	, url:' /	tags-list			 '	},
    {id:	56	, name: 	 ' 	R console	 ' 	, type:	 ' 	IDE	 ' 	, url:' /	tags-list			 '	},
    {id:	57	, name: 	 ' 	Cinema 4D	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list			 '	},
    {id:	58	, name: 	 ' 	After Effects	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list			 '	},
    {id:	59	, name: 	 ' 	Photoshop 	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list			 '	},
    {id:	60	, name: 	 ' 	Illustrator	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list			 '	},
    {id:	61	, name: 	 ' 	Animate	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list			 '	},
    {id:	62	, name: 	 ' 	Lightroom	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list			 '	},
    {id:	63	, name: 	 ' 	DxO	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list			 '	},
    {id:	64	, name: 	 ' 	Phase One	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list			 '	},
    {id:	65	, name: 	 ' 	Matlab	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list			 '	},
    {id:	66	, name: 	 ' 	Blender	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list			 '	},
    {id:	67	, name: 	 ' 	Unreal engine 5	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list			 '	},
    {id:	68	, name: 	 ' 	Mandelbulber	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list			 '	},
    {id:	69	, name: 	 ' 	DDlab	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list			 '	},
    {id:	70	, name: 	 ' 	Yasara	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list			 '	},
    {id:	71	, name: 	 ' 	instant-ngp	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list			 '	},
    {id:	72	, name: 	 ' 	BioEdit	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list			 '	},
    {id:	73	, name: 	 ' 	Geneious prime	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list			 '	},
    {id:	74	, name: 	 ' 	Agisoft-metashape	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list			 '	},
    {id:	75	, name: 	 ' 	Ready	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list			 '	},
    {id:	76	, name: 	 ' 	Webflow	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list			 '	},
    {id:	77	, name: 	 ' 	Bubble	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list			 '	},
    {id:	78	, name: 	 ' 	Arcgis Geophylobuilder	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list			 '	},
    {id:	79	, name: 	 ' 	Avogadro	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list			 '	},
    {id:	80	, name: 	 ' 	Meshlab	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list			 '	},
    {id:	81	, name: 	 ' 	Excel	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list			 '	},
    {id:	82	, name: 	 ' 	Lottie for After Effects	 ' 	, type:	 ' 	plugins	 ' 	, url:' /	tags-list			 '	},
    {id:	83	, name: 	 ' 	Insydium x-particles	 ' 	, type:	 ' 	plugins	 ' 	, url:' /	tags-list			 '	},
    {id:	84	, name: 	 ' 	Realflow	 ' 	, type:	 ' 	plugins	 ' 	, url:' /	tags-list			 '	},
    {id:	85	, name: 	 ' 	Octane Vectron	 ' 	, type:	 ' 	plugins	 ' 	, url:' /	tags-list			 '	},
    {id:	86	, name: 	 ' 	PDBLoader	 ' 	, type:	 ' 	plugins	 ' 	, url:' /	tags-list			 '	},
    {id:	87	, name: 	 ' 	Cinema 4D Physical	 ' 	, type:	 ' 	Moteurs de rendu	 ' 	, url:' /	tags-list			 '	},
    {id:	88	, name: 	 ' 	Octane render	 ' 	, type:	 ' 	Moteurs de rendu	 ' 	, url:' /	tags-list			 '	},
    {id:	89	, name: 	 ' 	Cycles	 ' 	, type:	 ' 	Moteurs de rendu	 ' 	, url:' /	tags-list			 '	},
    {id:	90	, name: 	 ' 	Sketch&Toon	 ' 	, type:	 ' 	Moteurs de rendu	 ' 	, url:' /	tags-list			 '	},
    {id:	91	, name: 	 ' 	HTML	 ' 	, type:	 ' 	Language	 ' 	, url:' /	tags-list			 '	},
    {id:	92	, name: 	 ' 	CSS	 ' 	, type:	 ' 	Language	 ' 	, url:' /	tags-list			 '	},
    {id:	93	, name: 	 ' 	javascript	 ' 	, type:	 ' 	Language	 ' 	, url:' /	tags-list			 '	},
    {id:	94	, name: 	 ' 	python	 ' 	, type:	 ' 	Language	 ' 	, url:' /	tags-list			 '	},
    {id:	95	, name: 	 ' 	R	 ' 	, type:	 ' 	Language	 ' 	, url:' /	tags-list			 '	},
    {id:	96	, name: 	 ' 	Three.js	 ' 	, type:	 ' 	Librairie	 ' 	, url:' /	tags-list			 '	},
    {id:	97	, name: 	 ' 	D3.js	 ' 	, type:	 ' 	Librairie	 ' 	, url:' /	tags-list			 '	},
    {id:	98	, name: 	 ' 	Plotly	 ' 	, type:	 ' 	Librairie	 ' 	, url:' /	tags-list			 '	},
    {id:	99	, name: 	 ' 	Matplotlib	 ' 	, type:	 ' 	Librairie	 ' 	, url:' /	tags-list			 '	},
    {id:	100	, name: 	 ' 	Numpy	 ' 	, type:	 ' 	Librairie	 ' 	, url:' /	tags-list			 '	},
    {id:	101	, name: 	 ' 	Pandas	 ' 	, type:	 ' 	Librairie	 ' 	, url:' /	tags-list			 '	},
    {id:	102	, name: 	 ' 	NetworkX	 ' 	, type:	 ' 	Librairie	 ' 	, url:' /	tags-list			 '	},
    {id:	103	, name: 	 ' 	Biopython	 ' 	, type:	 ' 	Librairie	 ' 	, url:' /	tags-list			 '	},
    {id:	104	, name: 	 ' 	Phylotools	 ' 	, type:	 ' 	Librairie	 ' 	, url:' /	tags-list			 '	},
    {id:	105	, name: 	 ' 	NerfStudio	 ' 	, type:	 ' 	Librairie	 ' 	, url:' /	tags-list			 '	},
    {id:	106	, name: 	 ' 	Instant-ngp	 ' 	, type:	 ' 	Librairie	 ' 	, url:' /	tags-list			 '	},
    {id:	107	, name: 	 ' 	XYZtoOBJ.py	 ' 	, type:	 ' 	Librairie	 ' 	, url:' /	tags-list			 '	},
    {id:	108	, name: 	 ' 	3d mol.js	 ' 	, type:	 ' 	Librairie	 ' 	, url:' /	tags-list			 '	},
    {id:	109	, name: 	 ' 	Anaconda	 ' 	, type:	 ' 	Plateforme	 ' 	, url:' /	tags-list			 '	},
    {id:	110	, name: 	 ' 	Google Cloud Computing platform	 ' 	, type:	 ' 	Plateforme	 ' 	, url:' /	tags-list			 '	},
    {id:	111	, name: 	 ' 	AWS EC2	 ' 	, type:	 ' 	Plateforme	 ' 	, url:' /	tags-list			 '	},
    {id:	112	, name: 	 ' 	MacOS	 ' 	, type:	 ' 	Environnement	 ' 	, url:' /	tags-list			 '	},
    {id:	113	, name: 	 ' 	Windows 10	 ' 	, type:	 ' 	Environnement	 ' 	, url:' /	tags-list			 '	},
    {id:	114	, name: 	 ' 	Linux scientific	 ' 	, type:	 ' 	Environnement	 ' 	, url:' /	tags-list			 '	},
    {id:	115	, name: 	 ' 	Jupyterlab	 ' 	, type:	 ' 	Environnement	 ' 	, url:' /	tags-list			 '	},
    {id:	116	, name: 	 ' 	Ubuntu	 ' 	, type:	 ' 	Environnement	 ' 	, url:' /	tags-list			 '	},
    {id:	117	, name: 	 ' 	Conda	 ' 	, type:	 ' 	Environnement	 ' 	, url:' /	tags-list			 '	},
    {id:	118	, name: 	 ' 	Astronomy	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list			 '	},
    {id:	119	, name: 	 ' 	Molecular biology	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list			 '	},
    {id:	120	, name: 	 ' 	Photogrammetry	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list			 '	},
    {id:	121	, name: 	 ' 	Meteorology	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list			 '	},
    {id:	122	, name: 	 ' 	Organic physics	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list			 '	},
    {id:	123	, name: 	 ' 	Phylogenetic	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list			 '	},
    {id:	124	, name: 	 ' 	Particle physics	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list			 '	},
    {id:	125	, name: 	 ' 	Virtual reality	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list			 '	},
    {id:	126	, name: 	 ' 	Sociolgy	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list			 '	},
    {id:	127	, name: 	 ' 	Graph theory	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list			 '	},
    {id:	128	, name: 	 ' 	Simulation	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list			 '	},
    {id:	129	, name: 	 ' 	Typography	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list			 '	},
    {id:	130	, name: 	 ' 	Statistics	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list			 '	},
    {id:	131	, name: 	 ' 	Maths	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list			 '	},
    {id:	132	, name: 	 ' 	Music	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list			 '	},
    {id:	133	, name: 	 ' 	Thermodynamics	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list			 '	},
    {id:	134	, name: 	 ' 	Science-fiction	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list			 '	},
    {id:	135	, name: 	 ' 	Topography	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list			 '	},
    {id:	136	, name: 	 ' 	Dynamic systems 	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list			 '	},
    {id:	137	, name: 	 ' 	bla 8	 ' 	, type:	 ' 	idem	 ' 	, url:' /	tags-list			 '	},
    {id:	138	, name: 	 ' 	Évolutive biology 	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list			 '	},
    {id:	139	, name: 	 ' 	Chaos theory	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list			 '	},
    {id:	140	, name: 	 ' 	data-visualisation	 ' 	, type:	 ' 	Nature	 ' 	, url:' /	tags-list			 '	},
    {id:	141	, name: 	 ' 	3D mesh visualisation	 ' 	, type:	 ' 	Nature	 ' 	, url:' /	tags-list			 '	},
    {id:	142	, name: 	 ' 	tracks visualisation	 ' 	, type:	 ' 	Nature	 ' 	, url:' /	tags-list			 '	},
    {id:	143	, name: 	 ' 	neural network	 ' 	, type:	 ' 	Nature	 ' 	, url:' /	tags-list			 '	},
    {id:	144	, name: 	 ' 	motion-design	 ' 	, type:	 ' 	Nature	 ' 	, url:' /	tags-list			 '	},
    {id:	145	, name: 	 ' 	graphic-design	 ' 	, type:	 ' 	Nature	 ' 	, url:' /	tags-list			 '	},
    {id:	146	, name: 	 ' 	animation	 ' 	, type:	 ' 	Nature	 ' 	, url:' /	tags-list			 '	},
    {id:	147	, name: 	 ' 	3D interactive	 ' 	, type:	 ' 	Nature	 ' 	, url:' /	tags-list			 '	},
    {id:	148	, name: 	 ' 	2D interactive	 ' 	, type:	 ' 	Dimension	 ' 	, url:' /	tags-list			 '	},
    {id:	149	, name: 	 ' 	3D animation	 ' 	, type:	 ' 	Dimension	 ' 	, url:' /	tags-list			 '	},
    {id:	150	, name: 	 ' 	2D animation	 ' 	, type:	 ' 	Dimension	 ' 	, url:' /	tags-list			 '	},
    {id:	151	, name: 	 ' 	Particle-system 	 ' 	, type:	 ' 	Nature	 ' 	, url:' /	tags-list			 '	},

       ];
