const nodes = [
    {id:	1	, name: 	 ' 	Astral map	 '	,info:'	Nuage de points interactif en 3D	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	astral-map		 '	},
{id:	2	, name: 	 ' 	Bacteriophage ms2 capsid protein : RNA complex   	 '	,info:'	Visualisation de grandes structures biomoléculaires	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	bacteriophage-ms2-capsid-protein-rna-complex		 '	},
{id:	3	, name: 	 ' 	Infernal spiral	 '	,info:'	Histogramme interactif en CSS	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	infernal-spiral		 '	},
{id:	4	, name: 	 ' 	Phylogenèse	 '	,info:'	Arbre phylogénétique en 3D	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	phylogenese		 '	},
{id:	5	, name: 	 ' 	Baboon/human comparison	 '	,info:'	Visualisation d\'alignement d\'ADN	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	baboon-human-comparison		 '	},
{id:	6	, name: 	 ' 	CMS collisions	 '	,info:'	Visualisation de trajectoires de particules	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	cms-collisions		 '	},
{id:	7	, name: 	 ' 	Politics	 '	,info:'	Graphes en reseau non-orienté	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	politics		 '	},
{id:	8	, name: 	 ' 	Star wars interactions	 '	,info:'	Graphes en reseau non-orienté	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	star-wars-interactions		 '	},
{id:	9	, name: 	 ' 	NERF(s)	 '	,info:'	Champs de radiance neurale	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	nerfs		 '	},
{id:	10	, name: 	 ' 	Souvenir	 '	,info:'	Simulation de nuage de points en 3D	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	souvenir		 '	},
{id:	11	, name: 	 ' 	Le bal des nuées oiseaux	 '	,info:'	Simulation de comportement de groupe (Boids)	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	le-bal-des-sardines		 '	},
{id:	12	, name: 	 ' 	La danse des bancs de poissons	 '	,info:'	Simulation de comportement de groupe (Boids)	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	le-bal-des-sardines		 '	},
{id:	13	, name: 	 ' 	Mirage festival 	 '	,info:'	Affiche animée	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	mirage-festival		 '	},
{id:	14	, name: 	 ' 	Mirage festival 	 '	,info:'	Affiche animée	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	mirage-festival		 '	},
{id:	15	, name: 	 ' 	Dimension festival	 '	,info:'	Affiche animée	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	dimension-festival		 '	},
{id:	16	, name: 	 ' 	L’origine du monde	 '	,info:'	Fractales en 3 dimension	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	l-origine-du-monde		 '	},
{id:	17	, name: 	 ' 	Synesthésies	 '	,info:'	Kit graphique	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	synesthesies		 '	},
{id:	18	, name: 	 ' 	Desigual	 '	,info:'	Visuel 3D	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	desigual		 '	},
{id:	19	, name: 	 ' 	Emergence	 '	,info:'	Simulation de reaction-diffusion	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	emergence		 '	},
{id:	20	, name: 	 ' 	Année 2090	 '	,info:'	Animation	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	annee-2090		 '	},
{id:	21	, name: 	 ' 	Assises Internationales du Roman	 '	,info:'	Affiche animée	 ' 	, type:	 ' 	project	 ' 	, url:' /	project/	assises-internationales-du-roman		 '	},
{id:	22	, name: 	 ' 	.json	 '	,info:'	Format de fichier pour stocker des données structurées en texte.	 ' 	, type:	 ' 	data-file-extension	 ' 	, url:' /	tags-list/	json		 '	},
{id:	23	, name: 	 ' 	.csv	 '	,info:'	Format de fichier de données tabulaires, avec des valeurs séparées par des virgules.	 ' 	, type:	 ' 	data-file-extension	 ' 	, url:' /	tags-list/	csv		 '	},
{id:	24	, name: 	 ' 	.pdb	 '	,info:'	Format de fichier pour stocker des informations sur la structure tridimensionnelle des molécules.	 ' 	, type:	 ' 	data-file-extension	 ' 	, url:' /	tags-list/	pdb		 '	},
{id:	25	, name: 	 ' 	.nex	 '	,info:'	Format de fichier pour représenter des données en phylogénie, notamment des arbres phylogénétiques.	 ' 	, type:	 ' 	data-file-extension	 ' 	, url:' /	tags-list/	nex		 '	},
{id:	26	, name: 	 ' 	.obj	 '	,info:'	Format de fichier pour stocker des modèles 3D avec géométrie et textures.	 ' 	, type:	 ' 	data-file-extension	 ' 	, url:' /	tags-list/	obj		 '	},
{id:	27	, name: 	 ' 	.xml	 '	,info:'	Format de fichier de balisage extensible utilisé pour structurer des données.	 ' 	, type:	 ' 	data-file-extension	 ' 	, url:' /	tags-list/	xml		 '	},
{id:	28	, name: 	 ' 	.xyz 	 '	,info:'	Coordonnées cartésiennes XYZ utilisées pour représenter des positions tridimensionnelles.	 ' 	, type:	 ' 	data-file-extension	 ' 	, url:' /	tags-list/	xyz		 '	},
{id:	29	, name: 	 ' 	.geojson	 '	,info:'	Format de fichier pour stocker des données géospatiales au format JSON.	 ' 	, type:	 ' 	data-file-extension	 ' 	, url:' /	tags-list/	geojson		 '	},
{id:	30	, name: 	 ' 	.newick	 '	,info:'	Format de fichier pour représenter des arbres phylogénétiques en biologie évolutive.	 ' 	, type:	 ' 	data-file-extension	 ' 	, url:' /	tags-list/	newick		 '	},
{id:	31	, name: 	 ' 	.gltf 	 '	,info:'	Format de fichier pour la transmission de modèles 3D, utilisé dans les applications web et les jeux.	 ' 	, type:	 ' 	data-file-extension	 ' 	, url:' /	tags-list/	gltf		 '	},
{id:	32	, name: 	 ' 	xyz cartesian coordinates	 '	,info:'	Coordonnées tridimensionnelles en utilisant les axes X, Y et Z.	 ' 	, type:	 ' 	data type	 ' 	, url:' /	tags-list/	xyz-cartesian-coordinates		 '	},
{id:	33	, name: 	 ' 	mesh	 '	,info:'	Structure tridimensionnelle composée de sommets, arêtes et faces, utilisée pour représenter des objets 3D.	 ' 	, type:	 ' 	data type	 ' 	, url:' /	tags-list/	mesh		 '	},
{id:	34	, name: 	 ' 	décimal (float)	 '	,info:'	Type de données numériques pour stocker des nombres décimaux à virgule flottante.	 ' 	, type:	 ' 	data type	 ' 	, url:' /	tags-list/	decimal-float		 '	},
{id:	35	, name: 	 ' 	Atomicité 	 '	,info:'	Concept d\'indivisibilité d\'une opération ou d\'une particule élémentaire.	 ' 	, type:	 ' 	data type	 ' 	, url:' /	tags-list/	atomicite		 '	},
{id:	36	, name: 	 ' 	sequence alignment matrix/taxonomy /trees	 '	,info:'	Concepts en bioinformatique pour comparer, classer et représenter des séquences génétiques.	 ' 	, type:	 ' 	data type	 ' 	, url:' /	tags-list/	sequence-alignment-matrix-taxonomy-trees		 '	},
{id:	37	, name: 	 ' 	tracks / vectors	 '	,info:'	Termes utilisés en mathématiques et en informatique pour décrire des trajectoires ou des directions.	 ' 	, type:	 ' 	data type	 ' 	, url:' /	tags-list/	tracks-vectors		 '	},
{id:	38	, name: 	 ' 	cameras positions alignement	 '	,info:'	Processus d\'alignement des positions de caméras pour la création d\'animations ou de modèles 3D.	 ' 	, type:	 ' 	data type	 ' 	, url:' /	tags-list/	cameras-positions-alignement		 '	},
{id:	39	, name: 	 ' 	edges	 '	,info:'	Les bords d\'un graphe, utilisés en théorie des graphes pour relier des sommets.	 ' 	, type:	 ' 	data type	 ' 	, url:' /	tags-list/	edges		 '	},
{id:	40	, name: 	 ' 	.jpeg	 '	,info:'	Format de fichier d\'image fixe	 ' 	, type:	 ' 	data-file-extension	 ' 	, url:' /	tags-list/	jpeg		 '	},
{id:	41	, name: 	 ' 	.gif	 '	,info:'	Format de fichier d\'image animée	 ' 	, type:	 ' 	data-file-extension	 ' 	, url:' /	tags-list/	gif		 '	},
{id:	42	, name: 	 ' 	Ableton	 '	,info:'	Ableton est un logiciel de production musicale et de performance en direct.	 ' 	, type:	 ' 	idem	 ' 	, url:' /	tags-list/	projets		 '	},
{id:	43	, name: 	 ' 	Substance Designer	 '	,info:'	Substance Designer est un logiciel de création de textures et de matériaux 3D utilisé dans l\'industrie du jeu vidéo, du cinéma et de la modélisation 3D	 ' 	, type:	 ' 	idem	 ' 	, url:' /	tags-list/	projets		 '	},
{id:	44	, name: 	 ' 	MapMap	 '	,info:'	MapMap est un logiciel open source de mapping vidéo en temps réel. Il est utilisé pour projeter des vidéos et des images sur des surfaces variées, créant ainsi des installations artistiques interactives. 	 ' 	, type:	 ' 	idem	 ' 	, url:' /	tags-list/	projets		 '	},
{id:	45	, name: 	 ' 	Mocap 4 All	 '	,info:'	Mocap 4 All est une plateforme open source de capture de mouvement (motion capture) basée sur l\'intelligence artificielle 	 ' 	, type:	 ' 	idem	 ' 	, url:' /	tags-list/	projets		 '	},
{id:	46	, name: 	 ' 	Rokoko	 '	,info:'	Rokoko est une entreprise qui propose des solutions de capture de mouvement accessibles pour les créateurs et les professionnels de l\'animation.	 ' 	, type:	 ' 	idem	 ' 	, url:' /	tags-list/	projets		 '	},
{id:	47	, name: 	 ' 	Touch Designer	 '	,info:'	TouchDesigner est une plateforme de développement visuel pour la création d\'installations interactives, d\'expériences en direct et d\'œuvres multimédias.	 ' 	, type:	 ' 	idem	 ' 	, url:' /	tags-list/	projets		 '	},
{id:	48	, name: 	 ' 	spline 3D	 '	,info:'	web-app de conception 3D pour le web	 ' 	, type:	 ' 	idem	 ' 	, url:' /	tags-list/	projets		 '	},
{id:	49	, name: 	 ' 	formulas	 '	,info:'	Équations ou règles mathématiques utilisées pour résoudre des problèmes ou effectuer des calculs.	 ' 	, type:	 ' 	data type	 ' 	, url:' /	tags-list/	formulas		 '	},
{id:	50	, name: 	 ' 	points cloud coordinates, Vertex RGB color	 '	,info:'	Données pour représenter des nuages de points 3D avec des couleurs associées.	 ' 	, type:	 ' 	data type	 ' 	, url:' /	tags-list/	points-cloud-coordinates-vertex-rgb-color		 '	},
{id:	51	, name: 	 ' 	Dictionary 	 '	,info:'	Structure de données associant des clés à des valeurs, utilisée pour le stockage et la récupération rapides d\'informations.	 ' 	, type:	 ' 	IDE	 ' 	, url:' /	tags-list/	dictionary		 '	},
{id:	52	, name: 	 ' 	Jupyter notepad 	 '	,info:'	Application de notebook interactif couramment utilisée en science des données et en programmation.	 ' 	, type:	 ' 	IDE	 ' 	, url:' /	tags-list/	jupyter-notepad		 '	},
{id:	53	, name: 	 ' 	Visual Studio Code	 '	,info:'	Environnement de développement intégré (IDE) couramment utilisé pour la programmation.	 ' 	, type:	 ' 	IDE	 ' 	, url:' /	tags-list/	visual-studio-code		 '	},
{id:	54	, name: 	 ' 	Codepen	 '	,info:'	Plateforme en ligne pour l\'édition de code HTML, CSS et JavaScript.	 ' 	, type:	 ' 	IDE	 ' 	, url:' /	tags-list/	codepen		 '	},
{id:	55	, name: 	 ' 	Github	 '	,info:'	Plateforme de gestion de versions et de collaboration pour le développement de logiciels.	 ' 	, type:	 ' 	IDE	 ' 	, url:' /	tags-list/	github		 '	},
{id:	56	, name: 	 ' 	R console	 '	,info:'	Interface en ligne de commande pour le langage de programmation R, utilisé en statistiques et analyse de données.	 ' 	, type:	 ' 	IDE	 ' 	, url:' /	tags-list/	r-console		 '	},
{id:	57	, name: 	 ' 	Cinema 4D	 '	,info:'	Logiciel de modélisation et d\'animation 3D.	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list/	cinema-4d		 '	},
{id:	58	, name: 	 ' 	After Effects	 '	,info:'	Logiciel d\'animation et de composition vidéo.	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list/	after-effects		 '	},
{id:	59	, name: 	 ' 	Photoshop 	 '	,info:'	Logiciel de retouche d\'image et de graphisme.	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list/	photoshop		 '	},
{id:	60	, name: 	 ' 	Illustrator	 '	,info:'	Logiciel de création de graphiques vectoriels.	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list/	illustrator		 '	},
{id:	61	, name: 	 ' 	Animate	 '	,info:'	Logiciel d\'animation vectorielle.	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list/	animate		 '	},
{id:	62	, name: 	 ' 	Lightroom	 '	,info:'	Logiciel de retouche photo et de gestion de bibliothèque.	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list/	lightroom		 '	},
{id:	63	, name: 	 ' 	DxO	 '	,info:'	Logiciel de traitement d\'images et d\'amélioration de la qualité photo.	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list/	dxo		 '	},
{id:	64	, name: 	 ' 	Phase One	 '	,info:'	Logiciel de traitement d\'images pour la photographie professionnelle.	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list/	phase-one		 '	},
{id:	65	, name: 	 ' 	Matlab	 '	,info:'	Environnement de programmation et de calcul numérique.	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list/	matlab		 '	},
{id:	66	, name: 	 ' 	Blender	 '	,info:'	Logiciel de modélisation et d\'animation 3D open source.	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list/	blender		 '	},
{id:	67	, name: 	 ' 	Unreal engine 5	 '	,info:'	Moteur de jeu pour le développement de jeux vidéo.	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list/	unreal-engine-5		 '	},
{id:	68	, name: 	 ' 	Mandelbulber	 '	,info:'	Logiciel de rendu d\'images fractales 3D.	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list/	mandelbulber		 '	},
{id:	69	, name: 	 ' 	DDlab	 '	,info:'	Discrete dynamic lab est un logiciel graphique interactif permettant de rechercher des réseaux dynamiques discrets, pertinents pour l\'étude de la complexité, des phénomènes émergents, des réseaux neuronaux et biomoléculaires	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list/	ddlab		 '	},
{id:	70	, name: 	 ' 	Yasara	 '	,info:'	Logiciel de modélisation moléculaire et de visualisation 3D.	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list/	yasara		 '	},
{id:	71	, name: 	 ' 	instant-ngp	 '	,info:'	Logiciel pour la création d\'animations 3D interactives.	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list/	instant-ngp		 '	},
{id:	72	, name: 	 ' 	BioEdit	 '	,info:'	Logiciel pour l\'édition et l\'analyse de séquences biologiques.	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list/	bioedit		 '	},
{id:	73	, name: 	 ' 	Geneious prime	 '	,info:'	Logiciel de bioinformatique pour l\'analyse de séquences génétiques.	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list/	geneious-prime		 '	},
{id:	74	, name: 	 ' 	Agisoft-metashape	 '	,info:'	Logiciel de photogrammétrie pour la création de modèles 3D à partir de photos.	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list/	agisoft-metashape		 '	},
{id:	75	, name: 	 ' 	Ready	 '	,info:'	Logiciel de visualisation de données géospatiales.	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list/	ready		 '	},
{id:	76	, name: 	 ' 	Webflow	 '	,info:'	Plateforme pour la création de sites web sans codage.	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list/	webflow		 '	},
{id:	77	, name: 	 ' 	Bubble	 '	,info:'	Plateforme de développement d\'applications sans codage.	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list/	bubble		 '	},
{id:	78	, name: 	 ' 	Arcgis Geophylobuilder	 '	,info:'	Outil pour la construction d\'arbres phylogénétiques.	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list/	arcgis-geophylobuilder		 '	},
{id:	79	, name: 	 ' 	Avogadro	 '	,info:'	Logiciel pour la visualisation moléculaire et la modélisation 3D.	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list/	avogadro		 '	},
{id:	80	, name: 	 ' 	Meshlab	 '	,info:'	Logiciel pour le traitement et la visualisation de maillages 3D.	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list/	meshlab		 '	},
{id:	81	, name: 	 ' 	Excel	 '	,info:'	Logiciel de tableur couramment utilisé.	 ' 	, type:	 ' 	Programm	 ' 	, url:' /	tags-list/	excel		 '	},
{id:	82	, name: 	 ' 	Lottie for After Effects	 '	,info:'	Bibliothèque pour l\'intégration d\'animations dans des applications.	 ' 	, type:	 ' 	plugins	 ' 	, url:' /	tags-list/	lottie-for-after-effects		 '	},
{id:	83	, name: 	 ' 	Insydium x-particles	 '	,info:'	Plugin de particules pour Cinema 4D.	 ' 	, type:	 ' 	plugins	 ' 	, url:' /	tags-list/	insydium-x-particles		 '	},
{id:	84	, name: 	 ' 	Realflow	 '	,info:'	Logiciel de simulation de fluides.	 ' 	, type:	 ' 	plugins	 ' 	, url:' /	tags-list/	realflow		 '	},
{id:	85	, name: 	 ' 	Octane Vectron	 '	,info:'	Moteur de rendu pour la génération d\'effets visuels 3D.	 ' 	, type:	 ' 	plugins	 ' 	, url:' /	tags-list/	octane-vectron		 '	},
{id:	86	, name: 	 ' 	PDBLoader	 '	,info:'	Plugin pour le chargement de fichiers PDB (Protein Data Bank) dans Cinema 4D.	 ' 	, type:	 ' 	plugins	 ' 	, url:' /	tags-list/	pdbloader		 '	},
{id:	87	, name: 	 ' 	Cinema 4D Physical	 '	,info:'	Moteur de rendu pour Cinema 4D.	 ' 	, type:	 ' 	Moteurs de rendu	 ' 	, url:' /	tags-list/	cinema-4d-physical		 '	},
{id:	88	, name: 	 ' 	Octane render	 '	,info:'	Moteur de rendu pour la création de graphismes 3D.	 ' 	, type:	 ' 	Moteurs de rendu	 ' 	, url:' /	tags-list/	octane-render		 '	},
{id:	89	, name: 	 ' 	Cycles	 '	,info:'	Moteur de rendu pour Blender.	 ' 	, type:	 ' 	Moteurs de rendu	 ' 	, url:' /	tags-list/	cycles		 '	},
{id:	90	, name: 	 ' 	Sketch&Toon	 '	,info:'	Module de rendu pour Cinema 4D permettant de créer des rendus de style dessin animé.	 ' 	, type:	 ' 	Moteurs de rendu	 ' 	, url:' /	tags-list/	sketch-toon		 '	},
{id:	91	, name: 	 ' 	HTML	 '	,info:'	Langage de balisage pour créer des pages web.	 ' 	, type:	 ' 	Language	 ' 	, url:' /	tags-list/	html		 '	},
{id:	92	, name: 	 ' 	CSS	 '	,info:'	Langage de style pour la mise en forme des pages web.	 ' 	, type:	 ' 	Language	 ' 	, url:' /	tags-list/	css		 '	},
{id:	93	, name: 	 ' 	javascript	 '	,info:'	Langage de programmation pour le développement web.	 ' 	, type:	 ' 	Language	 ' 	, url:' /	tags-list/	javascript		 '	},
{id:	94	, name: 	 ' 	python	 '	,info:'	Langage de programmation polyvalent couramment utilisé.	 ' 	, type:	 ' 	Language	 ' 	, url:' /	tags-list/	python		 '	},
{id:	95	, name: 	 ' 	R	 '	,info:'	Langage de programmation pour les statistiques et l\'analyse de données.	 ' 	, type:	 ' 	Language	 ' 	, url:' /	tags-list/	r		 '	},
{id:	96	, name: 	 ' 	Three.js	 '	,info:'	Bibliothèque JavaScript pour la création d\'applications 3D dans un navigateur web.	 ' 	, type:	 ' 	Librairie	 ' 	, url:' /	tags-list/	three-js		 '	},
{id:	97	, name: 	 ' 	D3.js	 '	,info:'	Bibliothèque JavaScript pour la création de visualisations de données interactives.	 ' 	, type:	 ' 	Librairie	 ' 	, url:' /	tags-list/	d3-js		 '	},
{id:	98	, name: 	 ' 	Plotly	 '	,info:'	Bibliothèque pour la création de graphiques interactifs en Python et JavaScript.	 ' 	, type:	 ' 	Librairie	 ' 	, url:' /	tags-list/	plotly		 '	},
{id:	99	, name: 	 ' 	Matplotlib	 '	,info:'	Bibliothèque pour la création de graphiques en Python.	 ' 	, type:	 ' 	Librairie	 ' 	, url:' /	tags-list/	matplotlib		 '	},
{id:	100	, name: 	 ' 	Numpy	 '	,info:'	Bibliothèque pour la manipulation de tableaux et de données en Python.	 ' 	, type:	 ' 	Librairie	 ' 	, url:' /	tags-list/	numpy		 '	},
{id:	101	, name: 	 ' 	Pandas	 '	,info:'	Bibliothèque pour la manipulation de données en Python.	 ' 	, type:	 ' 	Librairie	 ' 	, url:' /	tags-list/	pandas		 '	},
{id:	102	, name: 	 ' 	NetworkX	 '	,info:'	Bibliothèque pour l\'analyse de graphes en Python.	 ' 	, type:	 ' 	Librairie	 ' 	, url:' /	tags-list/	networkx		 '	},
{id:	103	, name: 	 ' 	Biopython	 '	,info:'	Bibliothèque pour la bioinformatique en Python.	 ' 	, type:	 ' 	Librairie	 ' 	, url:' /	tags-list/	biopython		 '	},
{id:	104	, name: 	 ' 	Phylotools	 '	,info:'	Outils pour l\'analyse phylogénétique.	 ' 	, type:	 ' 	Librairie	 ' 	, url:' /	tags-list/	phylotools		 '	},
{id:	105	, name: 	 ' 	NerfStudio	 '	,info:'	Plateforme pour la création d\'animations et de simulations 3D interactives.	 ' 	, type:	 ' 	Librairie	 ' 	, url:' /	tags-list/	nerfstudio		 '	},
{id:	106	, name: 	 ' 	Instant-ngp	 '	,info:'	Logiciel pour la création d\'animations 3D interactives.	 ' 	, type:	 ' 	Librairie	 ' 	, url:' /	tags-list/	instant-ngp		 '	},
{id:	107	, name: 	 ' 	XYZtoOBJ.py	 '	,info:'	Script Python pour la conversion de fichiers XYZ en OBJ.	 ' 	, type:	 ' 	Librairie	 ' 	, url:' /	tags-list/	xyztoobj-py		 '	},
{id:	108	, name: 	 ' 	3d mol.js	 '	,info:'	Bibliothèque JavaScript pour la visualisation de structures moléculaires en 3D.	 ' 	, type:	 ' 	Librairie	 ' 	, url:' /	tags-list/	3d-mol-js		 '	},
{id:	109	, name: 	 ' 	Anaconda	 '	,info:'	Plateforme de gestion de paquets et d\'environnements pour Python.	 ' 	, type:	 ' 	Plateforme	 ' 	, url:' /	tags-list/	anaconda		 '	},
{id:	110	, name: 	 ' 	Google Cloud Computing platform	 '	,info:'	Plateforme de services cloud de Google.	 ' 	, type:	 ' 	Plateforme	 ' 	, url:' /	tags-list/	google-cloud-computing-platform		 '	},
{id:	111	, name: 	 ' 	AWS EC2	 '	,info:'	Service d\'infrastructure cloud d\'Amazon Web Services.	 ' 	, type:	 ' 	Plateforme	 ' 	, url:' /	tags-list/	aws-ec2		 '	},
{id:	112	, name: 	 ' 	MacOS	 '	,info:'	Système d\'exploitation d\'Apple pour les ordinateurs Mac.	 ' 	, type:	 ' 	Environnement	 ' 	, url:' /	tags-list/	macos		 '	},
{id:	113	, name: 	 ' 	Windows 10	 '	,info:'	Système d\'exploitation de Microsoft pour les ordinateurs personnels.	 ' 	, type:	 ' 	Environnement	 ' 	, url:' /	tags-list/	windows-10		 '	},
{id:	114	, name: 	 ' 	Linux scientific	 '	,info:'	Distribution Linux conçue pour la recherche scientifique.	 ' 	, type:	 ' 	Environnement	 ' 	, url:' /	tags-list/	linux-scientific		 '	},
{id:	115	, name: 	 ' 	Jupyterlab	 '	,info:'	Environnement de développement interactif pour la science des données.	 ' 	, type:	 ' 	Environnement	 ' 	, url:' /	tags-list/	jupyterlab		 '	},
{id:	116	, name: 	 ' 	Ubuntu	 '	,info:'	Distribution Linux populaire.	 ' 	, type:	 ' 	Environnement	 ' 	, url:' /	tags-list/	ubuntu		 '	},
{id:	117	, name: 	 ' 	Conda	 '	,info:'	Gestionnaire de paquets et d\'environnements pour la programmation scientifique.	 ' 	, type:	 ' 	Environnement	 ' 	, url:' /	tags-list/	conda		 '	},
{id:	118	, name: 	 ' 	Astronomy	 '	,info:'	Domaine d\'étude scientifique axé sur l\'observation et la compréhension des objets célestes.	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list/	astronomy		 '	},
{id:	119	, name: 	 ' 	Molecular biology	 '	,info:'	Domaine de la biologie axé sur l\'étude des molécules biologiques et de la génétique.	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list/	molecular-biology		 '	},
{id:	120	, name: 	 ' 	Photogrammetry	 '	,info:'	Technique de mesure à partir de photographies pour créer des modèles 3D.	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list/	photogrammetry		 '	},
{id:	121	, name: 	 ' 	Meteorology	 '	,info:'	Science de l\'étude de l\'atmosphère et des phénomènes météorologiques.	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list/	meteorology		 '	},
{id:	122	, name: 	 ' 	Organic physics	 '	,info:'	Domaine de la physique qui se concentre sur les processus dans les systèmes biologiques.	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list/	organic-physics		 '	},
{id:	123	, name: 	 ' 	Phylogenetic	 '	,info:'	Domaine de la biologie étudiant les relations évolutives entre les espèces.	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list/	phylogenetic		 '	},
{id:	124	, name: 	 ' 	Particle physics	 '	,info:'	Branche de la physique étudiant les particules subatomiques et leurs interactions.	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list/	particle-physics		 '	},
{id:	125	, name: 	 ' 	Virtual reality	 '	,info:'	Technologie pour créer des environnements virtuels interactifs.	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list/	virtual-reality		 '	},
{id:	126	, name: 	 ' 	Sociolgy	 '	,info:'	Science sociale étudiant la société, les comportements humains et les interactions sociales.	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list/	sociolgy		 '	},
{id:	127	, name: 	 ' 	Graph theory	 '	,info:'	Branche des mathématiques étudiant les graphes et leurs propriétés.	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list/	graph-theory		 '	},
{id:	128	, name: 	 ' 	Simulation	 '	,info:'	Processus de création de modèles informatiques pour représenter le comportement de systèmes réels.	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list/	simulation		 '	},
{id:	129	, name: 	 ' 	Typography	 '	,info:'	Art et technique de disposition et de conception de texte.	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list/	typography		 '	},
{id:	130	, name: 	 ' 	Statistics	 '	,info:'	Domaine des mathématiques et de la science des données axé sur l\'analyse de données et la modélisation.	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list/	statistics		 '	},
{id:	131	, name: 	 ' 	Maths	 '	,info:'	Discipline des mathématiques, qui englobe divers domaines mathématiques.	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list/	maths		 '	},
{id:	132	, name: 	 ' 	Music	 '	,info:'	Art et science de la création et de la performance musicale.	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list/	music		 '	},
{id:	133	, name: 	 ' 	Thermodynamics	 '	,info:'	Branche de la physique étudiant les lois de la chaleur et de l\'énergie.	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list/	thermodynamics		 '	},
{id:	134	, name: 	 ' 	Science-fiction	 '	,info:'	Genre littéraire et cinématographique axé sur des concepts scientifiques imaginaires.	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list/	science-fiction		 '	},
{id:	135	, name: 	 ' 	Topography	 '	,info:'	Description et représentation des caractéristiques physiques de la surface terrestre.	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list/	topography		 '	},
{id:	136	, name: 	 ' 	Dynamic systems 	 '	,info:'	Étude de systèmes qui évoluent avec le temps, souvent caractérisés par des équations différentielles.	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list/	dynamic-systems		 '	},
{id:	137	, name: 	 ' 	Littérature	 '	,info:'	Écriture	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list/	ecriture		 '	},
{id:	138	, name: 	 ' 	Évolutive biology 	 '	,info:'	Sous-domaine de la biologie étudiant l\'évolution des espèces au fil du temps.	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list/	evolutive-biology		 '	},
{id:	139	, name: 	 ' 	Chaos theory	 '	,info:'	Branche des mathématiques et de la science étudiant les systèmes dynamiques sensibles aux conditions initiales.	 ' 	, type:	 ' 	Theme	 ' 	, url:' /	tags-list/	chaos-theory		 '	},
{id:	140	, name: 	 ' 	data-visualisation	 '	,info:'	Processus de représentation visuelle des données pour en faciliter la compréhension.	 ' 	, type:	 ' 	Nature	 ' 	, url:' /	tags-list/	data-visualisation		 '	},
{id:	141	, name: 	 ' 	3D mesh visualisation	 '	,info:'	Visualisation de modèles 3D et de maillages tridimensionnels.	 ' 	, type:	 ' 	Nature	 ' 	, url:' /	tags-list/	3d-mesh-visualisation		 '	},
{id:	142	, name: 	 ' 	tracks visualisation	 '	,info:'	Visualisation de trajectoires ou de chemins.	 ' 	, type:	 ' 	Nature	 ' 	, url:' /	tags-list/	tracks-visualisation		 '	},
{id:	143	, name: 	 ' 	neural network	 '	,info:'	Modèle computationnel inspiré du cerveau humain, utilisé en apprentissage automatique.	 ' 	, type:	 ' 	Nature	 ' 	, url:' /	tags-list/	neural-network		 '	},
{id:	144	, name: 	 ' 	motion-design	 '	,info:'	Processus de création de mouvements et d\'animations visuelles.	 ' 	, type:	 ' 	Nature	 ' 	, url:' /	tags-list/	motion-design		 '	},
{id:	145	, name: 	 ' 	graphic-design	 '	,info:'	Discipline de la création visuelle, notamment la conception graphique.	 ' 	, type:	 ' 	Nature	 ' 	, url:' /	tags-list/	graphic-design		 '	},
{id:	146	, name: 	 ' 	animation	 '	,info:'	Processus de création d\'images en mouvement.	 ' 	, type:	 ' 	Nature	 ' 	, url:' /	tags-list/	animation		 '	},
{id:	147	, name: 	 ' 	3D interactive	 '	,info:'	Contenu interactif en trois dimensions.	 ' 	, type:	 ' 	Nature	 ' 	, url:' /	tags-list/	3d-interactive		 '	},
{id:	148	, name: 	 ' 	2D interactive	 '	,info:'	Contenu interactif en deux dimensions.	 ' 	, type:	 ' 	Dimension	 ' 	, url:' /	tags-list/	2d-interactive		 '	},
{id:	149	, name: 	 ' 	3D animation	 '	,info:'	Animation en trois dimensions.	 ' 	, type:	 ' 	Dimension	 ' 	, url:' /	tags-list/	3d-animation		 '	},
{id:	150	, name: 	 ' 	2D animation	 '	,info:'	Animation en deux dimensions.	 ' 	, type:	 ' 	Dimension	 ' 	, url:' /	tags-list/	2D-animation		 '	},
{id:	151	, name: 	 ' 	Particle-system 	 '	,info:'	Système de particules utilisé pour simuler des phénomènes comme le feu, l\'eau, etc.	 ' 	, type:	 ' 	Nature	 ' 	, url:' /	tags-list/	particle-system		 '	},
															
       ];
